// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBirthDate: typeof import('./src/components/addBirthDate/AddBirthDate.vue')['default']
    AddBirthDatePanel: typeof import('./src/components/addBirthDate/AddBirthDatePanel.vue')['default']
    AddGroup: typeof import('./src/components/manageGroups/AddGroup.vue')['default']
    AddPersonChoices: typeof import('./src/components/AddPersonChoices.vue')['default']
    Chip: typeof import('./src/components/kit/Chip.vue')['default']
    ClearList: typeof import('./src/components/list/admin/ClearList.vue')['default']
    ConfirmationToast: typeof import('./src/components/addBirthDate/ConfirmationToast.vue')['default']
    ConfirmDeleteModal: typeof import('./src/components/list/ConfirmDeleteModal.vue')['default']
    ExpandablePanel: typeof import('./src/components/kit/ExpandablePanel.vue')['default']
    GoogleSignIn: typeof import('./src/components/TopMenu/GoogleSignIn.vue')['default']
    ImportantPersons: typeof import('./src/components/list/ImportantPersons.vue')['default']
    ImportExport: typeof import('./src/components/list/admin/ImportExport.vue')['default']
    ImportGoogleContactsModal: typeof import('./src/components/ImportGoogleContactsModal.vue')['default']
    ManageGroups: typeof import('./src/components/manageGroups/ManageGroups.vue')['default']
    ManageGroupsPanel: typeof import('./src/components/manageGroups/ManageGroupsPanel.vue')['default']
    Modal: typeof import('./src/components/kit/Modal.vue')['default']
    OnePerson: typeof import('./src/components/list/OnePerson.vue')['default']
    OrderBy: typeof import('./src/components/list/OrderBy.vue')['default']
    PersonDobAndAge: typeof import('./src/components/list/OnePerson/PersonDobAndAge.vue')['default']
    PersonGroups: typeof import('./src/components/list/OnePerson/PersonGroups.vue')['default']
    PersonKids: typeof import('./src/components/list/OnePerson/PersonKids.vue')['default']
    PersonName: typeof import('./src/components/list/OnePerson/PersonName.vue')['default']
    PersonParents: typeof import('./src/components/list/OnePerson/PersonParents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncLoader: typeof import('./src/components/TopMenu/SyncLoader.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu/TopMenu.vue')['default']
  }
}

export {}
